<script>
</script>

<button class="location">
    <span class="material-icons"> my_location </span>
</button>

<style>
    .location {
        background: #6e707a;
        width: 40px;
        height: 40px;
        color: #e7e7eb;
        border: none;
        border-radius: 50%;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }

    .location span {
        vertical-align: middle;
    }
</style>
